values:
  repo_URL: https://github.com/ForumViriumHelsinki/TFDS_SIMPL-open_data_provider.git
  branch: ${BRANCH}

project: ${PROJECT}
domainSuffix: ${DOMAINSUFFIX}
authorityDomainSuffix: ${AUTHORITYDOMAINSUFFIX}
namespaceTag:
  dataprovider: ${NAMESPACETAG}
  authority: ${AUTHNAMESPACETAG}
  common: ${COMMONSPACETAG}

resourcePreset: low

singleNode: ${SINGLENODE}

argocd:
  appname: ${NAMESPACE}
  namespace: ${ARGOCDNAMESPACE}

cluster:
  address: https://kubernetes.default.svc
  namespace: ${NAMESPACE}
  commonToolsNamespace: ${COMMONNAMESPACE}
  issuer: ${CLUSTERISSUER}

secrets:
  secretEngine: ${SECRETENGINE}
  role: ${SECRETROLE}

keycloak:
  enabled: true
  repo_URL: https://charts.bitnami.com/bitnami
  chart_name: keycloak
  targetRevision: 25.2.0
  keycloak_authenticator:
    targetRevision: 2.7.1
  eidas_demo_keycloak_extension:
    targetRevision: 0.4.1
  nameOverride: keycloak
  resourcesPreset: "none"
  resources:
    requests:
      cpu: "500m"
      memory: "1G"
    limits:
      cpu: "1"
      memory: "2G"
  valueFiles:
    - values.yaml

auth_provider:
  enabled: true
  projectID: "939"
  targetRevision: 2.12.4
  chart_name: authentication-provider
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  valueFiles:
    - values.yaml

auth_provider_fe:
  enabled: true
  projectID: "1308"
  targetRevision: 2.9.2
  chart_name: fe-authentication-provider
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

users_roles:
  enabled: true
  projectID: "771"
  targetRevision: 2.12.9
  chart_name: users-roles
  resources:
    requests:
      cpu: "250m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml

users_roles_fe:
  enabled: true
  projectID: "1310"
  targetRevision: 2.12.5
  chart_name: fe-users-and-roles
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

authentication_provider_fe:
  enabled: true
  projectID: "1308"
  targetRevision: 2.9.3
  chart_name: fe-authentication-provider
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

tier1_gateway:
  enabled: true
  projectID: "772"
  targetRevision: 2.12.6
  chart_name: tier1-gateway
  resources:
    requests:
      cpu: "250m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml

tier2_gateway:
  enabled: true
  projectID: "860"
  targetRevision: 2.11.4
  chart_name: tier2-gateway
  resources:
    requests:
      cpu: "250m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml
    - values-routes.yaml

tier2_proxy:
  enabled: true
  projectID: "1112"
  targetRevision: 1.5.5
  chart_name: tier2-proxy
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"

redis:
  enabled: true
  repo_URL: "https://charts.bitnami.com/bitnami"
  targetRevision: 19.6.0
  chart_name: redis
  nameOverride: redis
  resourcesPreset: "none"
  resources:
    requests:
      cpu: "0"
      memory: "0"
  valueFiles:
    - values.yaml

redis_commander:
  enabled: false
  repo_URL: "https://github.com/joeferner/redis-commander.git"
  targetRevision: master
  nameOverride: redis-commander
  path: "k8s/helm-chart/redis-commander"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  valueFiles:
    - values.yaml

signer:
  enabled: true
  projectID: "954"
  targetRevision: 0.0.10
  chart_name: signer
  serviceAccountName: signer-service-account
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml

simpl_edc:
  enabled: true
  projectID: "920"
  targetRevision: 1.0.23
  chart_name: edc
  nameOverride: simpl-edc
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml
    - values-consumer.yaml

simpl_catalogue_client:
  enabled: true
  projectID: "937"
  targetRevision: 2.4.0
  chart_name: catalogue-ui
  resources:
    requests:
      cpu: "250m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml

sd_ui:
  enabled: true
  projectID: "923"
  #targetRevision: "1.11.0"
  targetRevision: "1.8.1"
  chart_name: sd-ui
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml

edc_connector_adapter:
  enabled: true
  projectID: "1091"
  targetRevision: 1.15.0
  chart_name: edc-connector-adapter
  nameOverride: edc-connector-adapter
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml

files:
  enabled: true
  projectID: "978"
  targetRevision: 1.2.1
  chart_name: simpl-files
  nameOverride: simpl-files
  resources:
    requests:
      cpu: "250m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml

schema_sync_adapter:
  enabled: true
  projectID: "1324"
  targetRevision: 1.5.0
  chart_name: schema-sync-adapter
  nameOverride: schema-sync-adapter
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  valueFiles:
    - values.yaml

sdtooling_api_be:
  enabled: true
  projectID: "778"
  targetRevision: 1.26.0
  chart_name: sd-creation-wizard
  nameOverride: sd
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml

sdtooling_validation_api_be:
  enabled: true
  projectID: "868"
  targetRevision: 1.18.1
  chart_name: sd-creation-wizard
  nameOverride: sd-validation
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml

xfsc_advsearch_be:
  enabled: true
  projectID: "891"
  targetRevision: 1.20.0
  chart_name: xfsc-advsearch
  nameOverride: xfsc-advsearch-be
  resources:
    requests:
      cpu: "250m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  valueFiles:
    - values.yaml

monitoring:
  enabled: true
  projectID: "828"
  targetRevision: 0.5.4
  chart_name: eck-monitoring
  fullnameOverride: elastic
  resources:
    filebeat:
      requests:
        memory: "100Mi"
        cpu: "100m"
  valueFiles:
    - values.yaml

eidas:
  enabled: false
