apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'dataprovider-deployer'           # name of the deploying app in argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ForumViriumHelsinki/TFDS_SIMPL-open_data_provider.git'
    path: charts
    targetRevision: v3.0.6                   # version of package
    helm:
      values: |
        singleNode: true
        values:
          branch: v3.0.6                   # branch of repo with values - for released version it should be the release branch
        project: default
        namespaceTag:
          dataprovider: dataprovider      # identifier of deployment and part of fqdn for this agent
          common: common                 # identifier of deployment and part of fqdn for common components
        domainSuffix: idea.helsinki.tfds.io           # last part of fqdn
        resourcePreset: low             # set to "low" to disable requests of resources
        argocd:
          appname: dataprovider           # name of generated argocd app 
          namespace: argocd                 # namespace of your argocd
        cluster:
          address: https://kubernetes.default.svc
          namespace: dataprovider         # where the app will be deployed
          commonToolsNamespace: common    # namespace where main monitoring stack is deployed
          issuer: dev-prod                  # issuer of certificates
        secrets:
          role: example-role                # role created in OpenBao for access
          secretEngine: example             # secret engine name created in OpenBao
        crossplane:
          enabled: true                     # if infrastructure components should be deployed (there can be only one instance per cluster)
          kafka:
            username: user                  # name should be: namespace_infrabe e.g.: dataprovider01_infrabe
            password: pass                  # take the password from common01-kafka-credentials OpenBao secret, key dataprovider01_infrabe
          gitea:
            username: gitops_test           # username of gitea
            password: pass                  # password of gitea - the variable can take on any value (set it to your preference)
        monitoring:
          enabled: false                     # should monitoring be enabled
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dataprovider               # where the package will be deployed