apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'dataprovider-deployer'           # name of the deploying app in argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ForumViriumHelsinki/TFDS_SIMPL-open_data_provider.git'
    path: charts
    targetRevision: main                   # version of package
    helm:
      values: |
        singleNode: true
        values:
          branch: main                   # branch of repo with values - for released version it should be the release branch
        project: default
        namespaceTag:
          # These tags are injected into the middle of the FQDN strings.
          # Example: https://<service>.<namespaceTag>.<domainSuffix>
          dataprovider: dataprovider     # Creates URLs like: https://sd-ui.dataprovider.idea...
          authority: authority           # Creates URLs pointing to the central trust: https://tls.authority.authority.ds...
          common: common                 # Creates URLs pointing to shared infrastructure: https://secrets.common.idea...
        domainSuffix: idea.helsinki.tfds.io           # last part of fqdn for this provider
        authorityDomainSuffix: ds.helsinki.tfds.io    # last part of fqdn for the governance authority cluster
        resourcePreset: low             # set to "low" to disable requests of resources
        argocd:
          appname: dataprovider           # name of generated argocd app 
          namespace: argocd                 # namespace of your argocd
        cluster:
          address: https://kubernetes.default.svc
          namespace: dataprovider         # where the app will be deployed
          commonToolsNamespace: common    # namespace where main monitoring stack is deployed
          issuer: dev-prod                  # issuer of certificates
        secrets:
          role: example-role                # role created in OpenBao for access
          secretEngine: example             # secret engine name created in OpenBao
        crossplane:
          enabled: false                    # Set to true only if deploying on supported cloud providers (IONOS, OVH) to allow the agent to auto-provision infrastructure
          kafka:
            username: user                  # name should be: namespace_infrabe e.g.: dataprovider01_infrabe
            password: pass                  # take the password from common01-kafka-credentials OpenBao secret, key dataprovider01_infrabe
          gitea:
            username: gitops_test           # username of gitea
            password: pass                  # password of gitea - the variable can take on any value (set it to your preference)
        monitoring:
          enabled: false                     # should monitoring be enabled
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dataprovider               # where the package will be deployed