profile: participant

# Spring Cloud Gateway Routes Participant
appConfig:
  external-routes:
    rbac:
      - path: "/edc-connector-adapter/api/*/registration/register"
        method: GET
        roles:
          - SD_PUBLISHER
      - path: "/edc-connector-adapter/api/*/configuration/participant"
        method: POST
        roles:
          - SD_PUBLISHER
      - path: "/sdtooling-api/**"
        method: GET
        roles:
          - SD_PUBLISHER
      - path: "/sdtooling-api/**"
        method: POST
        roles:
          - SD_PUBLISHER
      - path: "/asset-orchestrator/**"
        method: GET
        roles:
          - SD_PUBLISHER
      - path: "/asset-orchestrator/**"
        method: POST
        roles:
          - SD_PUBLISHER
    logging:
      business:
      - config:
          operations:
          - ADVANCED_SEARCH
        method: POST
        path: /xfsc-advsearch-be/v1/selfDescriptions/advanced
      - config:
          operations:
          - QUICK_SEARCH
        method: GET
        path: /xfsc-advsearch-be/v1/selfDescriptions
  springdoc:
    swagger-ui:
      urls:
        - url: /userApi/openapi/usersroles-v1.yaml
          name: Users & Roles Service V1
        - url: /authApi/openapi/authenticationprovider-v1.yaml
          name: Authentication Provider Service V1
        - url: /openapi/tier1gateway-v1.yaml
          name: Application Info V1

  keycloak:
    app:
      realm: participant
