# Domain associated with Cluster
domain: integrated.simpl-europe.eu

# ID of persistentVolumeClaims associated with NFS Storage
schemaVolumeClaim: nfs-storage-pvc

# enable ingress only for development purpose
# on production environment this service must be exposted through the participant tier1 gateway only
ingress:
  enabled: false

log4j:
  level:
    # logging level for all logs excluding the specific ones
    root: INFO
    # logging level for application components only
    app: DEBUG
    # logging level for feign clients only
    feign: DEBUG

web:
  mvc:
    cors:
      # optional allowed origins for cross calls (separated by comma or * to allow all origins)
      # if empty no cross calls are allowed
      allowedOrigins: ""

# comma separated list of servers url to be used by swagger
openapiConfig:
  #servers: https://xsfc-advsearch-be.integrated.simpl-europe.eu,https://t1.data1-provider.integrated.simpl-europe.eu/xsfc-advsearch-be
  servers: https://xsfc-advsearch-be

# url to the AuthenticationProvider internal service
authenticationProvider:
  service:
    url: http://authentication-provider:8080

# absolute path to the schema repository synced by the schema-synch-adapter
schemaSyncService:
  repositoryPath: /home/simpluser/data/schemas/provider

# catalog adapter application (catalogue-adapter-service)
catalogueAdapter:
  tier2Gateway:
    # url to the tier2 tls gateway of the catalog adapter application
    url: https://tls.authority.authority.ds.helsinki.tfds.io
    #url: https://t2.gaiax-edc-dev-catalogue.dev.simpl-europe.eu
    # tier2 tls gateway path configured as route rule to the catalog adapter application
    pathPrefix: /adapter
    #pathPrefix: /catalogue-adapter-service

# federated catalog application
federatedCatalogue:
  tier2Gateway:
    # url to the tier2 tls gateway of the catalog adapter application
    url: https://tls.authority.authority.ds.helsinki.tfds.io
    #url: https://t2.gaiax-edc-dev-catalogue.dev.simpl-europe.eu
    # tier2 tls gateway path configured as route rule to the federated catalog application
    pathPrefix: /fc
    #pathPrefix: /fc-service
